### ISSUE TITLE
Timezone with quotes - DTSTART / DTEND

### ISSUE THREAD

**Issue by mesomorf1** [eouia/MMM-CalendarExt#68] opened 2019-09-22 05:13 UTC
My Exchange server generates the ics and uses quotes (") for the timezone that I use (here in Sweden) and that seams to be a problem in your Calendar module (works with other MM2 calendar modules)

The problem is that it does not show the appointment unless I select another timezone that does not get quoted. And UTC universial time seams to be the only one not quoted for me.

Example how it looks with quotes (not working): 

**DTSTART;TZID="(UTC+01:00) Amsterdam, Berlin, Bern, Rom, Stockholm, Wien":2019
 0924T130000
DTEND;TZID="(UTC+01:00) Amsterdam, Berlin, Bern, Rom, Stockholm, Wien":201909
 24T133000**

..so this works (gets generated without quotes, but wrong timezone for me):
**DTSTART;TZID=(UTC) Koordinerad universell tid:20190925T080000
DTEND;TZID=(UTC) Koordinerad universell tid:20190925T083000**

---

Complete .ics attached here:
[MyTest.ics.txt](https://github.com/eouia/MMM-CalendarExt/files/3639386/MyTest.ics.txt)

**Comment by eouia** [comment] 2019-10-27 15:52
Sorry for the late reply. I had not enough time to inspect this issue.
Your ics looks like not standard format. As my test, yours doesn't work in the default calendar module also.
Frankly said this module is using the same parser with the default calendar module of MM. So if mine couldn't parse, the default will be same.

Anyway, you can use `MMM-CalendarExt2`. It is using a new / better parser (I think. :D) and it could parse your ics.

![image](https://user-images.githubusercontent.com/1720610/67637346-0d3a6300-f8da-11e9-89cb-b5c7e48cc7f7.png)
I've changed the date to test 
```
DTSTART;TZID="(UTC+01:00) Amsterdam, Berlin, Bern, Rom, Stockholm, Wien":20191024T130000
DTEND;TZID="(UTC+01:00) Amsterdam, Berlin, Bern, Rom, Stockholm, Wien":20191024T133000
```

**Comment by eouia** [comment] 2020-01-16 09:36
No plan to fix this issue, because it is caused by invalid ical format. So I'll close this issue.

**Closed as completed by eouia** 2020-01-16 09:36 UTC
Labels: ToInspect
